# Generated by Django 4.1.7 on 2023-03-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_item',
            name='website',
            field=models.CharField(default='https://aserene.dev', max_length=100),
        ),
    ]
